#!/usr/bin/env python3

import argparse
import getpass
import os
import shutil
import subprocess
import tempfile
import time
import uuid
from pathlib import Path
from typing import Optional


def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()

    parser_prepare = subparsers.add_parser("prepare", help="Prepare base image")
    parser_prepare.add_argument("-i", "--image", type=Path, help="Image filename", required=True)
    parser_prepare.add_argument("-b", "--base", help="The base to prepare", default="base")
    parser_prepare.add_argument("-m", "--memory", type=int, help="Memory in MiB", default=1024)
    parser_prepare.add_argument("-d", "--disk", type=int, help="Disk in MiB", default=4096)
    parser_prepare.set_defaults(func=prepare)

    parser_update = subparsers.add_parser("update", help="Update base image")
    parser_update.add_argument("-b", "--base", help="The base to update", default="base")
    parser_update.add_argument("-m", "--memory", type=int, help="Memory in MiB", default=1024)
    parser_update.set_defaults(func=update)

    parser_run = subparsers.add_parser("run", help="Run an instance")
    parser_run.add_argument("-n", "--name", help="Name of the instance", default=f"instance-{int(time.time())}")
    parser_run.add_argument("-b", "--base", help="The base to use", default="base")
    parser_run.add_argument("-m", "--memory", type=int, help="Memory in MiB", default=1024)
    parser_run.set_defaults(func=run)

    args = parser.parse_args()
    if hasattr(args, "func") and args.func:
        args.func(args)
    else:
        parser.print_help()


def prepare(args):
    base_image = args.image
    if not base_image.is_file():
        print("Base image not found")
        raise SystemExit(1)
    base = args.base
    memory_mib = args.memory
    disk_mib = args.disk
    prepare_or_update(base_image, base, memory_mib, disk_mib)


def update(args):
    base = args.base
    memory_mib = args.memory
    prepare_or_update(None, base, memory_mib, None)


def prepare_or_update(base_image: Optional[Path], base: str, memory_mib: int, disk_mib: Optional[int]) -> None:
    name = base
    vm_uuid = str(uuid.uuid4())

    cache_dir = prepare_cache_dir()

    if base_image:
        shutil.copy(base_image, cache_dir / f"{base}.img")
        subprocess.run([
            "qemu-img",
            "resize",
            "-q",
            str(cache_dir / f"{base}.img"),
            f"{disk_mib}M"
        ],
            cwd=None,
            check=True)
    else:
        if not (cache_dir / f"{base}.img").is_file():
            print(f"Base {base} not found")
            raise SystemExit(1)

    temp_dir = Path(tempfile.mkdtemp())
    try:
        if base_image:
            cloud_init_prepare(name, temp_dir)
        else:
            cloud_init(name, temp_dir)

        run_vm(name, vm_uuid, cache_dir / f"{base}.img", temp_dir / f"{name}-seed.img", memory_mib,
               base_image is not None)
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def run(args):
    name = args.name
    base = args.base
    memory_mib = args.memory

    vm_uuid = str(uuid.uuid4())

    cache_dir = prepare_cache_dir()

    if not (cache_dir / f"{base}.img").is_file():
        print(f"Base {base} not found")
        raise SystemExit(1)

    temp_dir = Path(tempfile.mkdtemp())
    try:
        subprocess.run([
            "qemu-img",
            "create",
            "-q",
            "-f",
            "qcow2",
            "-b",
            str(cache_dir / f"{base}.img"),
            "-F",
            "qcow2",
            f"{name}.img",
        ], cwd=None, check=True)

        cloud_init(name, temp_dir)

        run_vm(name, vm_uuid, Path(f"{name}.img"), temp_dir / f"{name}-seed.img", memory_mib, is_prepare=False)
    finally:
        img_path = Path(f"{name}.img")
        if img_path.exists():
            img_path.unlink()
        shutil.rmtree(temp_dir, ignore_errors=True)


def cloud_init_prepare(name: str, temp_dir: Path):
    username = getpass.getuser()
    cols, rows = shutil.get_terminal_size()
    generate_cloud_init(
        name,
        temp_dir,
        f"""#cloud-config
growpart:
  mode: auto
  devices: [/]
  ignore_growroot_disabled: false
manage_etc_hosts: true
timezone: {read_timezone()}
user:
  name: \"{username}\"
  uid: \"{os.getuid()}\"
  groups: [adm, cdrom, dip, lxd, sudo]
  sudo: [\"ALL=(ALL) NOPASSWD:ALL\"]
  shell: /bin/bash
package_update: true
package_upgrade: true
write_files:
- path: /usr/lib/systemd/system/serial-getty@.service  
  content: |
    [Unit]
    Description=Serial Getty on %I
    Documentation=man:agetty(8) man:systemd-getty-generator(8)
    Documentation=https://0pointer.de/blog/projects/serial-console.html
    BindsTo=dev-%i.device
    After=dev-%i.device systemd-user-sessions.service plymouth-quit-wait.service getty-pre.target
    After=rc-local.service
    Before=getty.target
    IgnoreOnIsolate=yes
    Conflicts=rescue.service
    Before=rescue.service    
    [Service]
    ExecStart=-/sbin/agetty --noissue --noclear -a {username} -o '-p -f -- \\\\u' --keep-baud 115200,57600,38400,9600 - $TERM
    ExecStart=/sbin/shutdown -h --no-wall now
    Type=oneshot
    Restart=no
    UtmpIdentifier=%I
    StandardInput=tty
    StandardOutput=tty
    TTYPath=/dev/%I
    TTYReset=yes
    TTYVHangup=yes
    TTYColumns={cols}
    TTYRows={rows}
    IgnoreSIGPIPE=no
    SendSIGHUP=yes
    ImportCredential=agetty.*
    ImportCredential=login.*    
    [Install]
    WantedBy=getty.target
- path: /etc/default/grub.d/50-cloudimg-settings.cfg
  content: |
    GRUB_RECORDFAIL_TIMEOUT=0
    GRUB_TIMEOUT=0
    GRUB_CMDLINE_LINUX_DEFAULT="quiet console=ttyS0 systemd.getty_auto=no"
    GRUB_TERMINAL=console      
runcmd:
 - systemctl disable ssh
 - systemctl disable ssh.socket
 - systemctl disable getty@tty1.service
 - systemctl disable serial-getty@ttyS0.service
 - systemctl enable serial-getty@ttyS1.service
 - update-grub 
power_state:
  delay: now
  mode: poweroff
  timeout: 10
  condition: true
"""
    )


def cloud_init(name, temp_dir: Path):
    generate_cloud_init(
        name,
        temp_dir,
        f"""#cloud-config
growpart:
  mode: auto
  devices: [/]
  ignore_growroot_disabled: false
manage_etc_hosts: true
users: []
"""
    )


def read_timezone():
    try:
        return Path("/etc/timezone").read_text(encoding="utf-8").strip()
    except FileNotFoundError:
        return ""


def generate_cloud_init(name: str, temp_dir: Path, vendor_data: str):
    (temp_dir / "meta-data").write_text(f"""#cloud-config
instance-id: {name}
local-hostname: {name}
cloud-name: virter
""", encoding="utf-8")
    (temp_dir / "network-config").write_text("""#cloud-config
{}
""", encoding="utf-8")
    (temp_dir / "vendor-data").write_text(vendor_data, encoding="utf-8")
    (temp_dir / "user-data").write_text("""#cloud-config
{}
""", encoding="utf-8")

    subprocess.run([
        "genisoimage",
        "-quiet",
        "-output",
        f"{name}-seed.img",
        "-volid",
        "cidata",
        "-rational-rock",
        "-joliet",
        "meta-data",
        "network-config",
        "vendor-data",
        "user-data",
    ], cwd=(str(temp_dir)), check=True)


def prepare_cache_dir() -> Path:
    cache_home = os.environ.get("XDG_CACHE_HOME", str(Path.home() / ".cache"))
    cache_dir = Path(cache_home) / "virter"
    cache_dir.mkdir(parents=True, exist_ok=True)
    return cache_dir


def run_vm(name: str, vm_uuid: str, image: Path, cloud_init_image: Path, memory_mib: int, is_prepare: bool):
    subprocess.run(
        [
            "qemu-system-x86_64",
            "-name",
            name,
            "-uuid",
            vm_uuid,
            "-pidfile",
            f"{name}.pid",
            "-cpu",
            "host",
            "-accel",
            "kvm",
            "-m",
            str(memory_mib),
            "-nic",
            f"user,hostname={name}",
            "-drive",
            f"file={str(image)},index=0,format=qcow2,media=disk",
            "-drive",
            f"file={str(cloud_init_image)},index=1,media=cdrom",
            "-nographic",
            "-qmp",
            "null",
            "-chardev",
            "stdio,id=stdio,signal=off",
        ] + ([
                 "-serial",
                 "chardev:stdio",
             ]
             if is_prepare else
             [
                 "-serial",
                 "null",
                 "-serial",
                 "chardev:stdio",
             ]),
        cwd=None,
        check=True
    )


if __name__ == "__main__":
    main()
